import { randomBytes } from 'node:crypto';
import { spawn } from 'node:child_process';
import { access, realpath } from 'node:fs/promises';
import path from 'node:path';

const HELP = `Usage: node scripts/wbl-editor/start.mjs --record ABSOLUTE_PATH [options]

Starts the WBL Astro preview with development-only Editor Mode.

Options:
  --record PATH   Existing WBL Interface Editor change record (required)
  --port NUMBER   Local port, default 4321
  --host ADDRESS  Must be 127.0.0.1, default 127.0.0.1
  --token VALUE   Session token of at least 32 characters; generated by default
  -h, --help      Show this help
`;

function parse(argv) {
  const result = { host: '127.0.0.1', port: 4321, record: '', token: '' };
  for (let index = 0; index < argv.length; index += 1) {
    const argument = argv[index];
    if (argument === '-h' || argument === '--help') return { help: true };
    if (!['--record', '--port', '--host', '--token'].includes(argument)) {
      throw new Error(`Unknown option: ${argument}`);
    }
    const value = argv[index + 1];
    if (!value) throw new Error(`Missing value for ${argument}`);
    result[argument.slice(2)] = value;
    index += 1;
  }
  result.port = Number(result.port);
  return result;
}

let options;
try {
  options = parse(process.argv.slice(2));
} catch (error) {
  console.error(error.message);
  console.error(HELP);
  process.exit(1);
}

if (options.help) {
  console.log(HELP);
  process.exit(0);
}
if (!path.isAbsolute(options.record)) {
  throw new Error('--record must be an absolute path');
}
if (options.host !== '127.0.0.1') {
  throw new Error('--host must be 127.0.0.1');
}
if (!Number.isInteger(options.port) || options.port < 1024 || options.port > 65535) {
  throw new Error('--port must be an integer between 1024 and 65535');
}
const record = await realpath(options.record);
await access(path.join(record, 'change.json'));
const token = options.token || randomBytes(24).toString('hex');
if (token.length < 32) throw new Error('--token must contain at least 32 characters');

const astro = path.join(process.cwd(), 'node_modules/.bin/astro');
await access(astro);
const editorUrl = `http://${options.host}:${options.port}/?wblEdit=1&token=${encodeURIComponent(token)}`;

console.log(`WBL Editor URL: ${editorUrl}`);
console.log(`Agent session endpoint: http://${options.host}:${options.port}/__wbl-editor/session`);
console.log('Save applies only the frozen allowlisted batch. Publish is a separate explicit action.');

const child = spawn(
  astro,
  ['dev', '--host', options.host, '--port', String(options.port)],
  {
    cwd: process.cwd(),
    env: {
      ...process.env,
      WBL_EDITOR_ENABLED: '1',
      WBL_EDITOR_TOKEN: token,
      WBL_EDITOR_RECORD_ROOT: record,
    },
    stdio: 'inherit',
  },
);

for (const signal of ['SIGINT', 'SIGTERM']) {
  process.on(signal, () => child.kill(signal));
}
child.on('exit', (code, signal) => {
  if (signal) process.kill(process.pid, signal);
  process.exit(code ?? 1);
});
